services:
  yt_bot:
    build: .
    container_name: youtube_downloader_bot
    restart: always
    env_file:
      - .env
    depends_on:
      - pot_provider
    volumes:
      - ./downloads:/app/downloads

pot_provider:
    image: ghcr.io/jim60105/yt-dlp:pot
    container_name: pot_provider
    restart: always
    ports:
      - "8080:8080"
